#!/usr/bin/env python3
"""Turn a local D-50 ROM set into something the firmware can embed.

    python3 tools/d5_extract/d5_make_blob.py <romdir> <outdir>

Writes into <outdir>:
    d5_pcm.bin      262144 samples, 16-bit signed little-endian (512 KiB)
    d5_blob.S       assembly that pulls it in with .incbin
    d5_pcm_table.h  the frozen sample table as C++

The ROM stores each sample as a bit-permuted sign/log pair, which would cost a
64K-entry lookup table at runtime; decoding here instead makes the firmware
read plain 16-bit samples out of flash. 512 KiB is small enough for that to be
the obvious trade -- the JV and RD blobs are eight times larger.

The table comes from `d5_sample_table.json` next to this script, not from a
fresh derivation: it is frozen, and every entry carries how it was
established. No ROM data is in this repository -- see README.md.
"""
import json
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from d5_rom import D5RomSet, PAGE, SAMPLE_RATE  # noqa: E402

STUB = """// Generated by tools/d5_extract/d5_make_blob.py -- do not edit.
// The D-50 ROM images live outside the repository; this file only points at
// the copy the build step produced.
    .section .rodata
    .balign 4
    .global d5_pcm_blob
    .global d5_pcm_blob_end
d5_pcm_blob:
    .incbin "{pcm}"
d5_pcm_blob_end:
"""

HEADER = """// Generated by tools/d5_extract/d5_make_blob.py -- do not edit.
//
// The D-50's sample table is not in any ROM: the MB87136 resolves PCM numbers
// to addresses in its own mask ROM. This table was reconstructed from the
// decoded audio and verified by ear; `basis` records how each entry was
// established. See tools/d5_extract/README.md.
#pragma once

#include <cstdint>

namespace d5 {{

struct PcmSample {{
    uint32_t start;      // in samples, into d5_pcm_blob
    uint32_t length;     // 48..76: exactly one cycle, so the loop is the entry
    bool     looped;     // 48..76 are the sustained loops
    float    root_hz;    // 48..76 exact as 32000/length; attacks measured
    char     name[7];
}};

inline constexpr uint32_t kPcmSampleRate = {rate};
inline constexpr uint32_t kPcmWords      = {words};
inline constexpr int      kPcmCount      = {count};

inline constexpr PcmSample kPcmSamples[kPcmCount] = {{
{rows}
}};

}}  // namespace d5
"""


def root_hz(audio, start, end):
    """Measured fundamental of a region: autocorrelation over the steady part.

    The table carries no pitch -- the real one lives in the synth chip with
    the addresses -- so playback rates are derived from the material itself.
    Unpitched samples (noise, some percussion) report 0. Autocorrelation
    peaks just as hard at multiples of the true period, so the shortest
    submultiple that still correlates nearly as well wins; without that the
    three pianos come out 62/254/126 Hz instead of the octave series they
    audibly are.
    """
    import numpy as np
    skip = min(1024, (end - start) // 4)
    x = np.asarray(audio[start + skip: start + skip + 8192], dtype=np.float64)
    if len(x) < 512:
        x = np.asarray(audio[start:end], dtype=np.float64)
    if len(x) < 64:
        return 0.0
    x = x - x.mean()
    if float(np.max(np.abs(x))) < 1e-3:
        return 0.0
    # Spectral: the fundamental is the lowest prominent partial. On this
    # material that beats autocorrelation, whose peaks at 2x and 3x the true
    # period are just as strong and make the estimate jump by octaves.
    win = x * np.hanning(len(x))
    n = 1 << (len(win) * 4 - 1).bit_length()
    mag = np.abs(np.fft.rfft(win, n))
    freqs = np.arange(len(mag)) * (SAMPLE_RATE / n)
    band = (freqs > 40) & (freqs < 6000)
    mag = np.where(band, mag, 0.0)
    peak = float(mag.max())
    if peak <= 0:
        return 0.0
    # unpitched material (noise, some percussion) has no fundamental to find:
    # a flat spectrum means the lowest "peak" would be an arbitrary bin
    nz = mag[mag > 0]
    if len(nz) and float(np.exp(np.mean(np.log(nz))) / np.mean(nz)) > 0.25:
        return 0.0
    strong = np.flatnonzero(mag > 0.25 * peak)
    if len(strong) == 0:
        return 0.0
    k = int(strong[0])
    # parabolic interpolation around the bin for sub-bin accuracy
    if 0 < k < len(mag) - 1:
        a, b, c = mag[k - 1], mag[k], mag[k + 1]
        denom = a - 2 * b + c
        if denom != 0:
            k = k + 0.5 * (a - c) / denom
    # The interpolation can push bin 0 below zero, and a negative root pitch
    # inverts the playback rate. Only the attacks still come through here, but
    # it cost a puzzled half hour when a loop did.
    return max(0.0, float(k * (SAMPLE_RATE / n)))


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    romdir, outdir = sys.argv[1], sys.argv[2]
    os.makedirs(outdir, exist_ok=True)

    rs = D5RomSet(romdir)
    here = os.path.dirname(os.path.abspath(__file__))
    table = json.load(open(os.path.join(here, "d5_sample_table.json")))["samples"]

    pcm_path = os.path.join(outdir, "d5_pcm.bin")
    with open(pcm_path, "wb") as f:
        f.write(b"".join(
            struct.pack("<h", max(-32767, min(32767, int(v * 32767))))
            for v in rs.audio))

    with open(os.path.join(outdir, "d5_blob.S"), "w") as f:
        f.write(STUB.format(pcm=os.path.abspath(pcm_path)))

    rows = []
    for e in table:
        if e["start"] is None:
            # combination loops 77..100 are address ranges over the primary
            # material; carried as zero-length until they are resolved
            rows.append(f'    {{ 0, 0, true, 0.f, "{e["name"][:6]}" }},'
                        f'  // {e["pcm"]:3} {e["basis"]}')
        else:
            # The sustained loops carry their own pitch and it is exact:
            # each is one cycle of 2^k words, so the fundamental is
            # 32000/length to the last digit. Only the attacks, which have no
            # cycle to measure against, still go through the estimator.
            f0 = e.get("root_hz")
            if f0 is None:
                f0 = root_hz(rs.audio, e["start"], e["end"])
            rows.append(f'    {{ {e["start"]:6}, {e["end"] - e["start"]:6}, '
                        f'{"true " if e["looped"] else "false"}, {f0:8.2f}f, '
                        f'"{e["name"][:6]}" }},'
                        f'  // {e["pcm"]:3} {e["basis"]}')

    with open(os.path.join(outdir, "d5_pcm_table.h"), "w") as f:
        f.write(HEADER.format(rate=SAMPLE_RATE, words=len(rs.audio),
                              count=len(table), rows="\n".join(rows)))

    resolved = sum(1 for e in table if e["start"] is not None)
    print(f"wrote {pcm_path} ({os.path.getsize(pcm_path)/1024:.0f} KiB), "
          f"d5_blob.S and d5_pcm_table.h ({resolved}/{len(table)} samples resolved)")


if __name__ == "__main__":
    main()
