#!/usr/bin/env python3
"""Turn D-50 SysEx bulk dumps into a patch bank the firmware can embed.

    python3 tools/d5_extract/d5_syx_to_patches.py <bank.syx> [more.syx ...] <out_dir>

With several dump files the banks concatenate in argument order -- order is
the bank order the firmware will present, so put the factory bank first.

Writes `d5_patch_data.h`: the patches as raw D-50 parameter bytes, 448 per
patch, plus their names for the UI. The bytes stay raw on purpose. The
firmware converts them with `d5_patch_map.h`, so exactly one piece of code
knows what parameter 22 of a partial means -- and the same conversion can
later serve patches arriving over MIDI, which is the same format.

The dump is the machine's own: DT1 messages (F0 41 dev 14 12 aa bb cc ...),
address 02-00-00 upwards, 448 bytes per patch, seven 64-byte blocks each:

    upper partial 1, upper partial 2, upper common,
    lower partial 1, lower partial 2, lower common, patch

Roland's own manual lists those addresses with a gap; the layout above is what
the data shows, and the tool checks it -- every parameter has a documented
range, and a wrong block assignment breaks them immediately.
"""
import os
import sys

PATCH_BASE = 0x8000        # 02-00-00 in the D-50's 7-bit address space
PATCH_SIZE = 448
PATCH_COUNT = 64           # the patch area's own 64 slots; several dumps
                           # make several banks, one dump never does --
                           # what follows the 64th slot is the temp area
BLOCK = 64

# ' ', 'A'-'Z', 'a'-'z', '1'-'9', '0', '-' -- the panel's own character set
CHARS = (" ABCDEFGHIJKLMNOPQRSTUVWXYZ"
         "abcdefghijklmnopqrstuvwxyz1234567890-")

# (label, block index, offset, maximum) -- a sanity net: if the block layout
# were wrong, these would leave their ranges at once.
CHECKS = [
    ("structure (upper)", 2, 10, 6),
    ("structure (lower)", 5, 10, 6),
    ("chorus type", 2, 42, 7),
    ("key mode", 6, 18, 8),
    ("reverb type", 6, 30, 31),
    ("PCM wave number", 0, 7, 99),
    ("waveform", 0, 6, 1),
    ("TVF resonance", 0, 14, 30),
]

HEADER = """// Generated by tools/d5_extract/d5_syx_to_patches.py -- do not edit.
//
// {count} patches from {source}, as raw D-50 parameter bytes: 448 per patch,
// seven 64-byte blocks (upper partial 1 and 2, upper common, lower partial 1
// and 2, lower common, patch). d5_patch_map.h turns them into engine specs.
#pragma once

#include <cstdint>

namespace d5 {{

inline constexpr int kPatchCount = {count};
inline constexpr int kPatchBytes = 448;

inline constexpr char kPatchNames[{count}][19] = {{
{names}
}};

inline constexpr uint8_t kPatchData[{count}][448] = {{
{data}
}};

}}  // namespace d5
"""


def parse_sysex(raw):
    """Reassemble the dump's address space, checking every checksum."""
    mem = {}
    i = 0
    messages = 0
    while True:
        a = raw.find(b"\xf0", i)
        if a < 0:
            break
        b = raw.find(b"\xf7", a)
        if b < 0:
            break
        m = raw[a:b + 1]
        i = b + 1
        if len(m) < 10 or m[1] != 0x41 or m[3] != 0x14:
            continue                      # not a Roland D-50 message
        if m[4] != 0x12:                  # DT1; a handshake dump would be DAT
            continue
        addr = m[5] * 16384 + m[6] * 128 + m[7]
        data = m[8:-2]
        checksum = m[-2]
        total = sum(m[5:8]) + sum(data)
        if (128 - total % 128) % 128 != checksum:
            sys.exit(f"checksum mismatch in the message at address "
                     f"{m[5]:02X}-{m[6]:02X}-{m[7]:02X}")
        for k, v in enumerate(data):
            mem[addr + k] = v
        messages += 1
    if not messages:
        sys.exit("no D-50 data messages in this file")
    return mem, messages


def name_of(mem, base, length):
    out = []
    for i in range(length):
        v = mem.get(base + i, 0) & 0x3F
        out.append(CHARS[v])
    return "".join(out).rstrip()


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    srcs, outdir = sys.argv[1:-1], sys.argv[-1]
    patches = []
    names = []
    for src in srcs:
        mem, messages = parse_sysex(open(src, "rb").read())
        print(f"{os.path.basename(src)}: {messages} data messages, "
              f"{len(mem)} bytes, checksums all valid")
        found = 0
        p = 0
        while p < PATCH_COUNT and \
                PATCH_BASE + p * PATCH_SIZE + PATCH_SIZE - 1 in mem:
            base = PATCH_BASE + p * PATCH_SIZE
            patches.append(bytes(mem[base + i] for i in range(PATCH_SIZE)))
            names.append(name_of(mem, base + 6 * BLOCK, 18))
            found += 1
            p += 1
        if not found:
            sys.exit(f"{src} has no patch memory at address 02-00-00")
        print(f"  {found} patches")

    if not patches:
        sys.exit("no patches in any input")

    for label, blk, off, hi in CHECKS:
        vals = [b[blk * BLOCK + off] for b in patches]
        if min(vals) < 0 or max(vals) > hi:
            sys.exit(f"{label} is out of range ({min(vals)}..{max(vals)}, "
                     f"allowed 0..{hi}) -- the block layout does not hold")
    print(f"{len(patches)} patches, every checked parameter within range")

    os.makedirs(outdir, exist_ok=True)
    name_rows = ",\n".join(f'    "{n}"' for n in names)
    data_rows = []
    for body in patches:
        cells = ", ".join(str(v) for v in body)
        data_rows.append("    {" + cells + "}")
    path = os.path.join(outdir, "d5_patch_data.h")
    with open(path, "w") as f:
        f.write(HEADER.format(count=len(patches),
                              source=", ".join(os.path.basename(s)
                                               for s in srcs),
                              names=name_rows,
                              data=",\n".join(data_rows)))
    print(f"wrote {path} ({os.path.getsize(path) // 1024} KiB)")
    for i, n in enumerate(names[:8]):
        print(f"  {i // 8 + 1}-{i % 8 + 1}  {n}")
    if len(names) > 8:
        print(f"  ... and {len(names) - 8} more")


if __name__ == "__main__":
    main()
